# Generated by Django 5.2.15 on 2026-06-16 22:02

import apps.accounts.managers
import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models

# The role groups seeded on first migrate (DESIGN.md §4/§12 step 1). Kept as
# literals here so the migration is self-contained and immune to later refactors
# of the role-name constants in apps/accounts/roles.py.
SEED_ROLE_GROUPS = ["user", "developer", "admin"]


def seed_role_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for name in SEED_ROLE_GROUPS:
        Group.objects.get_or_create(name=name)


def remove_role_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=SEED_ROLE_GROUPS).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # citext must exist before the Account table's email column is created.
        CITextExtension(),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', apps.accounts.models.CIEmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('email_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_account',
            },
            managers=[
                ('objects', apps.accounts.managers.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_logintoken',
            },
        ),
        migrations.CreateModel(
            name='RoleGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('grant', 'grant'), ('revoke', 'revoke')], max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_grants_made', to=settings.AUTH_USER_MODEL)),
                ('target_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_grants_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_rolegrant',
            },
        ),
        migrations.RunPython(seed_role_groups, remove_role_groups),
    ]
