# Generated by Django 5.2.15 on 2026-06-24 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('update', 'update'), ('early_access', 'early access')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'updates_notice',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['app_id', 'published_at'], name='updates_app_published_idx')],
            },
        ),
    ]
