# Generated by Django 5.2.15 on 2026-06-21 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions_subscription',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='subscriptions_user_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'app_id'), name='subscriptions_one_per_user_app')],
            },
        ),
    ]
