# Generated by Django 5.2.15 on 2026-06-20 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_id', models.UUIDField()),
                ('score', models.PositiveSmallIntegerField()),
                ('review_text', models.TextField(blank=True, default='')),
                ('weight_eligible', models.BooleanField()),
                ('eligibility_basis', models.CharField(choices=[('curated_digest_impression', 'curated — DIGEST impression'), ('no_curated_impression', 'not curated — no qualifying impression'), ('curation_unverified', 'curation unverified (gate read failed)')], max_length=32)),
                ('eligibility_determined_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings_rating',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app_id', 'created_at'], name='ratings_app_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'app_id'), name='ratings_one_active_per_user_app')],
            },
        ),
    ]
