# Generated by Django 5.2.15 on 2026-06-26 13:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetReachCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('impression', 'widget render'), ('click_through', 'view-on-platform click')], max_length=16)),
                ('count_date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'widget_reach_count',
                'indexes': [models.Index(fields=['app_id', 'kind', 'count_date'], name='widget_reach_app_kind_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('app_id', 'kind', 'count_date'), name='widget_reach_count_unique')],
            },
        ),
    ]
