# Generated by Django 5.2.15 on 2026-06-27 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetConversionCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('follow', 'new follow of the clicked-through app'), ('account', 'new platform account')], max_length=16)),
                ('count_date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'widget_conversion_count',
                'indexes': [models.Index(fields=['app_id', 'kind', 'count_date'], name='widget_conv_app_kind_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('app_id', 'kind', 'count_date'), name='widget_conversion_count_unique')],
            },
        ),
    ]
