# Generated by Django 5.2.15 on 2026-06-18 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_id', models.UUIDField()),
                ('surface', models.CharField(choices=[('digest', 'weekly digest')], max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signals_impression',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('click_through', 'click-through'), ('subscribe', 'subscribe'), ('page_reengagement', 'on-page re-engagement'), ('share', 'share'), ('off_platform_proxy', 'off-platform proxy')], max_length=24)),
                ('app_id', models.UUIDField()),
                ('is_proxy', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_events', to=settings.AUTH_USER_MODEL)),
                ('impression', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='signals.impression')),
            ],
            options={
                'db_table': 'signals_engagement_event',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpressionTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_id', models.UUIDField()),
                ('impression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='signals.impression')),
            ],
            options={
                'db_table': 'signals_impression_tag',
            },
        ),
        migrations.CreateModel(
            name='PlatformVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signals_platform_visit',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.AddIndex(
            model_name='impression',
            index=models.Index(fields=['app_id', 'occurred_at'], name='signals_imp_app_time_idx'),
        ),
        migrations.AddIndex(
            model_name='impression',
            index=models.Index(fields=['occurred_at'], name='signals_imp_time_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementevent',
            index=models.Index(fields=['app_id', 'kind', 'occurred_at'], name='signals_evt_app_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementevent',
            index=models.Index(fields=['occurred_at'], name='signals_evt_time_idx'),
        ),
        migrations.AddIndex(
            model_name='impressiontag',
            index=models.Index(fields=['tag_id'], name='signals_imptag_tagid_idx'),
        ),
        migrations.AddConstraint(
            model_name='impressiontag',
            constraint=models.UniqueConstraint(fields=('impression', 'tag_id'), name='signals_impression_tag_unique'),
        ),
        migrations.AddIndex(
            model_name='platformvisit',
            index=models.Index(fields=['visit_date'], name='signals_visit_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='platformvisit',
            constraint=models.UniqueConstraint(fields=('user', 'visit_date'), name='signals_platform_visit_unique'),
        ),
    ]
