# Generated by Django 5.2.15 on 2026-06-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impression',
            name='surface',
            field=models.CharField(choices=[('digest', 'weekly digest'), ('app_page', 'app page')], max_length=16),
        ),
    ]
