# Generated by Django 5.2.15 on 2026-06-20 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_alter_impression_surface'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='impression',
            index=models.Index(fields=['user', 'app_id'], name='signals_imp_user_app_idx'),
        ),
    ]
