# Generated by Django 5.2.15 on 2026-06-17 18:30

import apps.catalog.models
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # citext must exist before the citext normalized_url column is created. Create it
        # idempotently (no dependency on another app's migration — DESIGN.md §1), and
        # deliberately do NOT drop it on reverse: citext is a shared Postgres extension
        # other apps (accounts.email, taxonomy.slug) also depend on, so dropping it here
        # would break `migrate catalog zero`. Reversing catalog drops only this app's four
        # tables (DESIGN.md §9 rollback), never the shared extension.
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS citext",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=2000)),
                ('normalized_url', apps.catalog.models.CITextField(max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('withdrawn', 'withdrawn')], default='pending', max_length=9)),
                ('last_submitted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_app',
                'ordering': ['-last_submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AppMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='app_media/%Y/%m/')),
                ('position', models.SmallIntegerField()),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.app')),
            ],
            options={
                'db_table': 'catalog_app_media',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='AppTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_id', models.UUIDField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_tags', to='catalog.app')),
            ],
            options={
                'db_table': 'catalog_app_tag',
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected')], max_length=8)),
                ('failed_criteria', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('works', 'Reachable & functional'), ('not_spam', 'Not malware or spam'), ('not_duplicate', 'Not a duplicate of a catalogued app'), ('honest_metadata', 'Metadata honestly describes the app'), ('policy', 'Meets basic platform policy')], max_length=20), blank=True, default=list, size=None)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='catalog.app')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_review_decision',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['status'], name='catalog_app_status_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['normalized_url'], name='catalog_app_normurl_idx'),
        ),
        migrations.AddConstraint(
            model_name='appmedia',
            constraint=models.UniqueConstraint(fields=('app', 'position'), name='catalog_app_media_position_unique'),
        ),
        migrations.AddIndex(
            model_name='apptag',
            index=models.Index(fields=['tag_id'], name='catalog_app_tag_tagid_idx'),
        ),
        migrations.AddConstraint(
            model_name='apptag',
            constraint=models.UniqueConstraint(fields=('app', 'tag_id'), name='catalog_app_tag_unique'),
        ),
    ]
