# Generated by Django 5.2.15 on 2026-06-29 22:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_backfill_accepted_at_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='deep_dive',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='app',
            name='demo_clip',
            field=models.FileField(blank=True, null=True, upload_to='app_clips/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='app',
            name='demo_clip_alt',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='app',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.CreateModel(
            name='AppFacet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facet', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=48)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_facets', to='catalog.app')),
            ],
            options={
                'db_table': 'catalog_app_facet',
                'indexes': [models.Index(fields=['app'], name='catalog_app_facet_app_idx')],
                'constraints': [models.UniqueConstraint(fields=('app', 'facet', 'value'), name='catalog_app_facet_unique')],
            },
        ),
    ]
