# Generated by Django 5.2.15 on 2026-06-17 11:33

import apps.taxonomy.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # citext must exist before the citext slug columns are created. Create it
        # idempotently (no dependency on an accounts migration — DESIGN.md §1), and
        # deliberately do NOT drop it on reverse: citext is a shared Postgres extension
        # that other apps (accounts.email) also depend on, so dropping it here would
        # break `migrate taxonomy zero`. Reversing taxonomy must drop only this app's
        # tables (DESIGN.md §9 rollback), never the shared extension.
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS citext",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', apps.taxonomy.models.CITextField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'taxonomy_cluster',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', apps.taxonomy.models.CITextField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('definition', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('retired', 'retired')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('clusters', models.ManyToManyField(blank=True, related_name='tags', to='taxonomy.cluster')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='taxonomy.tag')),
            ],
            options={
                'db_table': 'taxonomy_tag',
                'ordering': ['label'],
                'indexes': [models.Index(fields=['status'], name='taxonomy_tag_status_idx')],
                'constraints': [models.UniqueConstraint(apps.taxonomy.models.CanonicalLabel('label'), name='taxonomy_tag_label_canonical_unique')],
            },
        ),
    ]
